/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/settings/About.vue')['default']
    ActionGroup: typeof import('./src/components/ActionGroup.vue')['default']
    Appearance: typeof import('./src/components/settings/Appearance.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ContainerError: typeof import('./src/components/ContainerError.vue')['default']
    DockerStat: typeof import('./src/components/DockerStat.vue')['default']
    FileLogViewer: typeof import('./src/components/FileLogViewer.vue')['default']
    FileTextEditor: typeof import('./src/components/FileTextEditor.vue')['default']
    FloatingDialog: typeof import('./src/components/floating/FloatingDialog.vue')['default']
    FloatingMenu: typeof import('./src/components/floating/FloatingMenu.vue')['default']
    FloatingTooltip: typeof import('./src/components/floating/FloatingTooltip.vue')['default']
    General: typeof import('./src/components/settings/General.vue')['default']
    GlobalEnv: typeof import('./src/components/settings/GlobalEnv.vue')['default']
    HiddenInput: typeof import('./src/components/HiddenInput.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./src/components/settings/Security.vue')['default']
    StackList: typeof import('./src/components/StackList.vue')['default']
    StackListItem: typeof import('./src/components/StackListItem.vue')['default']
    Terminal: typeof import('./src/components/Terminal.vue')['default']
    TwoFADialog: typeof import('./src/components/TwoFADialog.vue')['default']
  }
}
