name: Close Incorrect Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  close-incorrect-issue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: npm

      - run: npm ci --no-fund

      - name: Close Incorrect Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: node extra/close-incorrect-issue.js
